-- All original executable scripts have been replaced by these reviewed modules.
local Config=require(script.Parent.Config)
local RS=game:GetService("ReplicatedStorage")
local SS=game:GetService("ServerStorage")
local net=assert(RS:FindFirstChild(Config.names[1]),"Encoded protocol folder is missing")
assert(net:FindFirstChild(Config.names[5]).Value==Config.version,"Protocol version mismatch")
assert(net:FindFirstChild(Config.names[6]).Value==Config.buildId,"Protocol build mismatch")
assert(not net:GetAttribute("Started"),"Duplicate FunCombat server startup")
net:SetAttribute("Started",true)
local templates=assert(SS:FindFirstChild("FunCombatData"),"Source dependencies are missing")
local Combat=require(script.Parent.CombatServer)
local World=require(script.Parent.World)
local Voting=require(script.Parent.Voting)
local combat=Combat.new({folder=net,config=Config},templates)
local world=World.new(combat,templates)
local voting=Voting.new(combat,world,templates.Maps)
world:start();combat:start();voting:start()
print("FunCombat server ready; protocol "..Config.version..", build "..Config.buildId)
